language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - PACKAGE_VCS_URL=https://github.com/aursu/rpmbuild-php-8.0
    - BINTRAY_REPO=php8custom
    - OS7=7.9.2009
    - OS8=8.3.2011
    - OS7TAG=7.9.2009
    - OS8TAG=8.3.2011
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BASE=centos7php80base BUILD=centos7php80    UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BASE=centos7php80base BUILD=centos7php80rel UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.el8.yml   BASE=centos8php80base BUILD=centos8php80    UPLOADER=centos8bintray
    - BUILD_COMPOSE_FILE=docker-compose.el8.yml   BASE=centos8php80base BUILD=centos8php80rel UPLOADER=centos8bintray

install:
  - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}

before_script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILD}

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} up --exit-code-from ${BUILD} ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
  on:
    all_branches: true

jobs:
  include:
    - stage: build
      before_install:
        - docker-compose -f rpmbuild/docker-compose.yml pull  centos7repo centos8repo webrepo
      install:
        - docker-compose -f rpmbuild/docker-compose.yml up -d centos7repo centos8repo webrepo
      before_script: skip
      script:
        - docker-compose -f build/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/docker-compose.yml push
        on:
          all_branches: true
    - stage: build
      before_install:
        - docker-compose -f rpmbuild/docker-compose.yml pull  centos7repo centos8repo webrepo
      install:
        - docker-compose -f rpmbuild/docker-compose.yml up -d  centos7repo centos8repo webrepo
      before_script: skip
      script:
        - docker-compose -f build/docker-compose.el8.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/docker-compose.el8.yml push
        on:
          all_branches: true
    - stage: runtime
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f run/docker-compose.yml push
        on:
          all_branches: true
    - stage: runtime
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.el8.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f run/docker-compose.el8.yml push
        on:
          all_branches: true
    - stage: dev
      install: skip
      before_script: skip
      script:
        - docker-compose -f run/docker-compose.dev.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f run/docker-compose.dev.yml push
        on:
          all_branches: true

stages:
  - test
  - build
  - runtime
  - dev
