version: "3.5"
services:
  centos8php80:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
  centos8php80rel:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8

volumes:
  rpms:
    name: rpms
  rpm8:
    name: rpm8
