version: "3.5"
services:
  centos7php80run:
    build:
      context: .
      args:
        centos: $OS7
    image: aursu/php80build:${OS7TAG}-runtime
  centos7php80devbase:
    build:
      context: .
      args:
        centos: $OS7
        image: nodedev
    image: aursu/php80build:${OS7TAG}-devbase
  centos7php80dev2base:
    build:
      context: .
      args:
        centos: $OS7
        image: node16dev
    image: aursu/php80build:${OS7TAG}-dev2base