version: "3.5"
services:
  centos8php80run:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
    image: aursu/php80build:${OS8TAG}-runtime
  centos8php80devbase:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: nodedev
        centos: $OS8
    image: aursu/php80build:${OS8TAG}-devbase
  centos8php80dev2base:
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        image: node16dev
        centos: $OS8
    image: aursu/php80build:${OS8TAG}-dev2base
